In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model


In [12]:
df=pd.read_csv("housepricing.csv")
df

area  bedroom  age   price
0  2100        2   10   50000
1  2600        2   10  550000
2  3000        3   20  620000
3  3200        3   30  680000
4  4000        5   40  720000

In [13]:
import math
median_room=math.floor(df.bedroom.median())
median_room

3

In [14]:
df.bedroom=df.bedroom.fillna(median_room)
df

area  bedroom  age   price
0  2100        2   10   50000
1  2600        2   10  550000
2  3000        3   20  620000
3  3200        3   30  680000
4  4000        5   40  720000

In [15]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedroom','age']],df.price)

LinearRegression()

In [20]:
reg.coef_

array([   1045.28301887, -342452.83018868,   -9245.28301887])

In [17]:
reg.intercept_

-1360188.679245246

In [19]:
reg.predict([[3000,3,20]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([563396.22641509])

In [21]:
1045.28301887*3000+-342452.83018868*3+-9245.28301887*20 + -1360188.679245246

563396.2264213138

In [25]:
reg.predict([[2500,2,10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([475660.3773585])